import {defineField, defineType, defineArrayMember} from 'sanity'

export const realisation = defineType({
  name: 'realisation',
  title: 'Réalisation',
  type: 'document',
  groups: [
    { name: 'card',     title: 'Carte & grille' },
    { name: 'page',     title: 'Page projet' },
    { name: 'results',  title: 'Résultats' },
    { name: 'quote',    title: 'Citation client' },
    { name: 'bridge',   title: 'Et pour votre marque ?' },
  ],
  fields: [
    // ── ORDRE D'AFFICHAGE ─────────────────────────────
    defineField({
      name: 'order',
      title: 'Ordre d\'affichage',
      description: 'Nombre entier — plus petit = affiché en premier.',
      type: 'number',
    }),

    // ── CARD FIELDS ──────────────────────────────────
    defineField({
      name: 'podcastName',
      title: 'Nom du podcast',
      description: 'Nom court affiché sur la carte et dans la modale de la page Réalisations.',
      type: 'string',
      group: 'card',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'projectTitle',
      title: 'Titre du projet (long)',
      description: 'Titre éditorial complet, utilisé sur la page Pourquoi et la page projet dédiée.',
      type: 'string',
      group: 'card',
    }),
    defineField({
      name: 'client',
      title: 'Client',
      type: 'string',
      group: 'card',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'card',
      options: {source: 'title', maxLength: 96},
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'sector',
      title: 'Secteur',
      type: 'string',
      group: 'card',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'format',
      title: 'Format',
      type: 'string',
      group: 'card',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'year',
      title: 'Année',
      type: 'string',
      group: 'card',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'cardImage',
      title: 'Image de carte',
      type: 'image',
      group: 'card',
      options: {hotspot: true},
    }),
    defineField({
      name: 'cardVideo',
      title: 'Vidéo de carte (URL)',
      type: 'url',
      group: 'card',
    }),
    defineField({
      name: 'cardBackground',
      title: 'Dégradé de fond (CSS)',
      description: 'Override du gradient de la carte et de la modale. Ex: radial-gradient(ellipse at 60% 40%, #c94f1a 0%, #7a2810 45%, #1e0a04 100%)',
      type: 'string',
      group: 'card',
    }),
    defineField({
      name: 'cardDescription',
      title: 'Description carte (accroche courte)',
      type: 'text',
      group: 'card',
      rows: 3,
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'projectSummary',
      title: 'Résumé page Pourquoi (facultatif)',
      description: 'Corps du bloc étude de cas sur la page Pourquoi un podcast. Si vide, la page utilisera cardDescription.',
      type: 'text',
      group: 'card',
      rows: 4,
    }),
    defineField({
      name: 'pourquoiTag',
      title: 'Tag Pourquoi (ex: Sensibiliser)',
      description: "Étiquette jaune affichée sur l'étude de cas (Sensibiliser, Convaincre, (In)former…).",
      type: 'string',
      group: 'card',
    }),
    defineField({
      name: 'featuredStatValue',
      title: 'Stat mise en avant — Valeur',
      description: 'Ex : 130 000',
      type: 'string',
      group: 'card',
    }),
    defineField({
      name: 'featuredStatLabel',
      title: 'Stat mise en avant — Label',
      description: 'Ex : écoutes · 5 saisons',
      type: 'string',
      group: 'card',
    }),
    defineField({
      name: 'hasProjectPage',
      title: 'Page projet dédiée ?',
      type: 'boolean',
      group: 'card',
      initialValue: false,
      validation: Rule => Rule.required(),
    }),

    // ── PAGE FIELDS ───────────────────────────────────
    defineField({
      name: 'award',
      title: 'Prix / Récompense',
      description: 'Ex : Prix Communication Santé. Affiché comme tag rouge sur la page projet.',
      type: 'string',
      group: 'page',
    }),
    defineField({
      name: 'projectIntro',
      title: 'Accroche héro (citation en italique)',
      description: 'Phrase d\'accroche affichée en hero page. Si vide, utilise la description carte.',
      type: 'text',
      group: 'page',
      rows: 3,
    }),
    defineField({
      name: 'challengeTitle',
      title: 'Titre du défi',
      description: 'Titre de la section "Le défi" sur la page projet. Si vide : "Le contexte du projet".',
      type: 'string',
      group: 'page',
    }),
    defineField({
      name: 'modalDescription',
      title: 'Description défi',
      description: 'Utilisé comme corps de la section "Le défi" sur la page projet.',
      type: 'text',
      group: 'page',
      rows: 5,
    }),
    defineField({
      name: 'strategyPoints',
      title: 'Approche stratégique',
      description: 'Liste de 2-4 points expliquant pourquoi le podcast était la bonne approche.',
      type: 'array',
      group: 'page',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({ name: 'title', type: 'string', title: 'Titre du point' }),
            defineField({ name: 'body',  type: 'text',   title: 'Explication', rows: 3 }),
          ],
          preview: { select: { title: 'title' } },
        }),
      ],
    }),
    defineField({
      name: 'solutionBody',
      title: 'La solution créative (corps)',
      description: 'Description de ce qui a été concrètement créé.',
      type: 'text',
      group: 'page',
      rows: 6,
    }),
    defineField({
      name: 'specs',
      title: 'Specs de production',
      description: '2-3 blocs Format / Durée / Distribution etc.',
      type: 'array',
      group: 'page',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({ name: 'label', type: 'string', title: 'Label (ex: Format)' }),
            defineField({ name: 'value', type: 'string', title: 'Valeur (ex: 4)' }),
            defineField({ name: 'sub',   type: 'string', title: 'Sous-texte (ex: Saisons produites)' }),
          ],
          preview: { select: { title: 'label', subtitle: 'value' } },
        }),
      ],
    }),
    defineField({
      name: 'audioEmbed',
      title: 'Embed audio (URL iframe)',
      type: 'url',
      group: 'page',
    }),
    defineField({
      name: 'videoFile',
      title: 'Vidéo ou audiogramme',
      type: 'file',
      group: 'page',
      options: { accept: 'video/*' },
      description: 'Clip vidéo ou audiogramme MP4 — max recommandé 100MB. Prioritaire sur l\'embed ci-dessous.',
    }),
    defineField({
      name: 'videoEmbed',
      title: 'Embed vidéo (URL iframe) — fallback',
      type: 'url',
      group: 'page',
    }),

    // ── RESULTS ──────────────────────────────────────
    defineField({ name: 'stat1Value',   title: 'Stat 1 — Valeur',   type: 'string', group: 'results' }),
    defineField({ name: 'stat1Label',   title: 'Stat 1 — Label',    type: 'string', group: 'results' }),
    defineField({ name: 'stat1Context', title: 'Stat 1 — Contexte', type: 'string', group: 'results' }),
    defineField({ name: 'stat2Value',   title: 'Stat 2 — Valeur',   type: 'string', group: 'results' }),
    defineField({ name: 'stat2Label',   title: 'Stat 2 — Label',    type: 'string', group: 'results' }),
    defineField({ name: 'stat2Context', title: 'Stat 2 — Contexte', type: 'string', group: 'results' }),
    defineField({ name: 'stat3Value',   title: 'Stat 3 — Valeur',   type: 'string', group: 'results' }),
    defineField({ name: 'stat3Label',   title: 'Stat 3 — Label',    type: 'string', group: 'results' }),
    defineField({ name: 'stat3Context', title: 'Stat 3 — Contexte', type: 'string', group: 'results' }),
    defineField({ name: 'stat4Value',   title: 'Stat 4 — Valeur',   type: 'string', group: 'results' }),
    defineField({ name: 'stat4Label',   title: 'Stat 4 — Label',    type: 'string', group: 'results' }),
    defineField({ name: 'stat4Context', title: 'Stat 4 — Contexte', type: 'string', group: 'results' }),

    // ── QUOTE ────────────────────────────────────────
    defineField({
      name: 'clientQuote',
      title: 'Citation client',
      type: 'text',
      group: 'quote',
      rows: 3,
    }),
    defineField({ name: 'clientQuoteName', title: 'Citation — Nom',  type: 'string', group: 'quote' }),
    defineField({ name: 'clientQuoteRole', title: 'Citation — Rôle', type: 'string', group: 'quote' }),

    // ── BRIDGE ───────────────────────────────────────
    defineField({
      name: 'bridgeBody',
      title: '"Et pour votre marque ?" — Corps',
      type: 'text',
      group: 'bridge',
      rows: 5,
    }),
    defineField({
      name: 'bridgeSectors',
      title: '"Et pour votre marque ?" — Secteurs cibles',
      type: 'array',
      group: 'bridge',
      of: [defineArrayMember({ type: 'string' })],
    }),
  ],
  preview: {
    select: {
      title: 'podcastName',
      subtitle: 'client',
      media: 'cardImage',
    },
  },
})
